spring:
  redis:
    database: 0
    host: 106.52.36.74
    port: 6379
    password: 123@456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  cache:
    cache-names: c1,c2
    redis:
      time-to-live: 1800s
