spring:
  rabbitmq:
    host: 106.52.36.74
    port: 5672
    username: admin
    password: admin
    virtual-host: /

    #启用消息失败返回，比如路由不到队列时触发回调
    publisher-returns: true
    listener:
      simple:
        #        acknowledge-mode: manual #采用手动应答
        concurrency: 3 #消费端最小并发数
        max-concurrency: 10 #消费端最大并发数
        prefetch: 3 #一次请求中预处理的消息数量

    publisher-confirm-type:


