spring:
  thymeleaf:
    #是否开启缓存，开发时可设置为 false，默认为 true
    cache: false
    #检查模板是否存在，默认为 true
    check-template: true
    #检查模板位置是否存在，默认为 true
    check-template-location: true
    #模板文件编码
    encoding: UTF-8
    #模板文件位置
    prefix: classpath:/templates/
    #Content-Type 配置
    servlet:
      content-type: text/html
    #模板文件后缀
    suffix: .html
  mvc:
    static-path-pattern: /aaa/**
  resources:
    static-locations: classpath:/static/
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: E:\\temp
      max-file-size: 1MB
      max-request-size: 10MB
      resolve-lazily: false
