shiro:
  # 表示开启Shiro配置，默认为true
  enabled: true
  # 表示登录地址，默认为"/login.jsp"
  loginUrl: /login
  # 表示登录成功地址，默认为"/"
  successUrl: /index
  # 表示未获授权默认跳转地址
  unauthorizedUrl: /unauthorized
  web:
    # 表示开启Shiro Web配置 默认为true
    enabled: true
  sessionManager:
    # 表示是否允许通过Cookie实现会话跟踪，默认为true
    sessionIdCookieEnabled: true
    # 表示是否允许通过URL参数实现会话跟踪，如果网站支持Cookie，可以关闭此选项，默认为true
    sessionIdUrlRewritingEnabled: true
