spring:
  mail:
    #发送邮件服务器
    host: smtp.qq.com
    port: 465
    username: 809477146@qq.com
    #授权码
    password: giknbnzirzydbdji
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  application:
    name: spring-boot-admin
  boot:
    admin:
      notify:
        mail:
          from: 809477146@qq.com
          to: 3250480014@qq.com
          cc: 1037439947@qq.com
          ignore-changes:
server:
  port: 8080
